"""Configuration file parser for Vicsek model simulations."""

from pathlib import Path
from typing import Dict, Any


class ConfigManager:
    """Parse configuration files for Vicsek model simulations."""
    
    @staticmethod
    def load(config_path: str) -> Dict[str, Any]:
        """
        Load configuration from file.
        
        File format:
            # Comments
            key = value
        
        Supported types: bool, int, float, str
        
        Args:
            config_path: Path to configuration file
        
        Returns:
            Dictionary of configuration parameters
        """
        path = Path(config_path)
        if not path.exists():
            raise FileNotFoundError(f"Config not found: {config_path}")
        
        config = {}
        
        with open(path, 'r') as f:
            for line in f:
                line = line.strip()
                
                # Skip empty/comment lines
                if not line or line.startswith('#'):
                    continue
                
                if '=' not in line:
                    continue
                
                # Parse key = value
                key, value = line.split('=', 1)
                key = key.strip()
                value = value.strip()
                
                # Remove inline comments
                if '#' in value:
                    value = value.split('#')[0].strip()
                
                # Parse type
                config[key] = ConfigManager._parse_value(value)
        
        return config
    
    @staticmethod
    def _parse_value(value: str) -> Any:
        """Parse string to appropriate Python type."""
        # Boolean
        if value.lower() in ['true', 'false']:
            return value.lower() == 'true'
        
        # Numeric
        try:
            if '.' in value or 'e' in value.lower():
                return float(value)
            else:
                return int(value)
        except ValueError:
            return value
    
    @staticmethod
    def save(config: Dict[str, Any], config_path: str):
        """
        Save configuration to file.
        
        Args:
            config: Configuration dictionary
            config_path: Output path
        """
        path = Path(config_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(path, 'w') as f:
            f.write("# 3D Vicsek Model Configuration\n")
            f.write("# Generated by manuk-kepudang\n\n")
            
            for key, value in sorted(config.items()):
                if isinstance(value, bool):
                    value_str = 'true' if value else 'false'
                elif isinstance(value, float):
                    if abs(value) < 1e-4 or abs(value) > 1e4:
                        value_str = f"{value:.2e}"
                    else:
                        value_str = f"{value}"
                else:
                    value_str = str(value)
                
                f.write(f"{key} = {value_str}\n")
    
    @staticmethod
    def validate_config(config: Dict[str, Any]) -> bool:
        """
        Validate configuration parameters.
        
        Args:
            config: Configuration dictionary
        
        Returns:
            True if valid
        
        Raises:
            ValueError: If configuration is invalid
        """
        required_keys = [
            'scenario_name', 'n_particles', 'box_size',
            'speed', 'interaction_radius', 'noise'
        ]
        
        for key in required_keys:
            if key not in config:
                raise ValueError(f"Missing required parameter: {key}")
        
        # Physical constraints
        if config.get('n_particles', 0) < 2:
            raise ValueError("n_particles must be >= 2")
        
        if config.get('box_size', 0) <= 0:
            raise ValueError("box_size must be > 0")
        
        if config.get('speed', 0) <= 0:
            raise ValueError("speed must be > 0")
        
        if config.get('interaction_radius', 0) <= 0:
            raise ValueError("interaction_radius must be > 0")
        
        if config.get('noise', -1) < 0:
            raise ValueError("noise must be >= 0")
        
        return True
